import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { PostProvider } from '@/providers/PostProvider';
import { posts } from '@/mock/posts';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostProvider posts={posts}>{children}</PostProvider>
      </body>
    </html>
  );
}
